[package]
name = "kroeg-tap-activitypub"
version = "0.1.0"
authors = ["Puck Meerburg <puck@puckipedia.com>"]

[dependencies]
serde_json = "1.0"
jsonld = { path = "../../jsonld-rs" }
kroeg-cellar = { path = "../../cellar" }
kroeg-tap = { path = "../tap" }
futures-await = "0.1"
