[package]
name = "kroeg-tap"
version = "0.1.0"
authors = ["Puck Meerburg <puck@puckipedia.com>"]

[dependencies]
serde_json = "1.0"
jsonld = { path = "../../jsonld-rs" }
chrono = "0.4"
futures-await = "0.1"
