name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      with:
        profile: minimal
        toolchain: nightly-2021-07-05
        override: true
        components: rustfmt
    - name: Run tests
      run: cargo test --verbose
